# Generated by Django 4.0.4 on 2022-05-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
